name: CloudSystem CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: CloudSystem Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - name: Maven Test
        run: |
          mvn -B test
      - name: Maven Clean Package
        run: |
          mvn -B clean package